noun1 = input("Noun: ")
adj1 = input("Adjective: ")
adj2 = input("Adjective: ")
verb1 = input("Verb: ")
name1 = input("Name: ")
noun2 = input("Noun: ")
verb2 = input("Verb: ")
ingverb1 = input("Verb ending in -ing: ")
adj3 = input("Adjective: ")
verb3 = input("Verb: ")
noun3 = input("Noun: ")

print(f"It was time to go to the haunted {noun1} in our town. Nobody goes there anymore, and it's {adj1} and {adj2}. It's considered as haunted from people who've been in there. Well, it's time to find out for myself. I {verb1} with my friend {name1} across the front yard. We came to the {noun2}, and we didn't even have to {verb2} it. It swung open by itself. {ingverb1} with {adj3}, we {verb3} inside the {noun3}.")
